//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSLintNet.Specifications.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSLintNet.Specifications.Tasks.TaskResources", typeof(TaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define([&apos;some-module&apos;], function (someModule) {
        ///    return someModule;
        ///});
        ///.
        /// </summary>
        internal static string AmdNoStrict {
            get {
                return ResourceManager.GetString("AmdNoStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*global define, ko*/
        ///
        ///define([], function () {
        ///    &apos;use strict&apos;;
        ///
        ///    return ko.applyBindings();
        ///});
        ///.
        /// </summary>
        internal static string GlobalVariableDef {
            get {
                return ResourceManager.GetString("GlobalVariableDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;output&quot;: &quot;Warning&quot;
        ///}
        ///.
        /// </summary>
        internal static string MessageSettings {
            get {
                return ResourceManager.GetString("MessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;output&quot;: &quot;Warning&quot;
        ///}
        ///.
        /// </summary>
        internal static string WarningSettings {
            get {
                return ResourceManager.GetString("WarningSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;
        ///
        ///var global = window.global;
        ///.
        /// </summary>
        internal static string WindowGlobalStrict {
            get {
                return ResourceManager.GetString("WindowGlobalStrict", resourceCulture);
            }
        }
    }
}
